<Project>
  <PropertyGroup>
    <Version>0.5.0</Version>
    <Authors>ErrorLSC</Authors>
    <RepositoryUrl>https://github.com/ErrorLSC/Polars.NET</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\THIRD_PARTY_LICENSES.html" Pack="true" PackagePath="\" />
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>