<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="OpsSpecs.fs" />
    <Compile Include="ExpressionPatterns.fs" />
    <Compile Include="ExprTranslator.fs" />
    <Compile Include="AggTranslator.fs" />
    <Compile Include="LinqReflectionCache.fs" />
    <Compile Include="PolarsQueryable.fs" />
  </ItemGroup>

<ItemGroup>
    <ProjectReference Include="..\Polars.NET.Core\Polars.NET.Core.csproj" />
</ItemGroup>

</Project>
