<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>

    <GenerateDocumentationFile>true</GenerateDocumentationFile> 

    <PackageId>Polars.NET.ML</PackageId> 
    <Title>Polars.NET and ML.NET Integration</Title>
    <Authors>ErrorLSC</Authors>
    <Description>The Machine Learning extension for Polars.NET. This package provides high-speed data bridges between Polars DataFrames, Apache Arrow memory, ML.NET (IDataView). Unlock hardware-accelerated SIMD math, train classic ML models, and seamlessly integrate with deep learning pipelines (ONNX).</Description>
    <PackageTags>polars;dataframe;machine-learning;mlnet;apache-arrow;data-science</PackageTags>
    <RepositoryUrl>https://github.com/ErrorLSC/Polars.NET</RepositoryUrl>
    <PackageProjectUrl>https://github.com/ErrorLSC/Polars.NET</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Polars.NET.Core\Polars.NET.Core.csproj" />
    <ProjectReference Include="..\Polars.CSharp\Polars.CSharp.csproj" />
    <ProjectReference Include="..\Polars.FSharp\Polars.FSharp.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Apache.Arrow" Version="23.0.0" />
    <PackageReference Include=" Microsoft.ML.DataView" Version="2.0.1" />
  </ItemGroup>
  
</Project>
