#pragma warning disable CS1591 
using Polars.NET.Core;
using LinqToDB.Internal.Linq;

namespace Polars.NET.Linq;
public static class PolarsQueryableExtensions
{
    public static IPolarsLazyFrame ToLazyFrame<T>(this IQueryable<T> query)
    {
        if (query is IExpressionQuery exprQuery && 
            exprQuery.DataContext is PolarsDataContext polarsDb)
        {
            var sqlQueries = exprQuery.GetSqlQueries(null);

            if (sqlQueries == null || sqlQueries.Count == 0)
                throw new InvalidOperationException("[Polars.NET] linq2db SQL generation failed");

            var rawSql = sqlQueries[0].Sql;

            var sanitizedSql = SqlSanitizer.Clean(rawSql); 

            return polarsDb.ExecuteToLazyFrame(sanitizedSql);
        }

        throw new InvalidOperationException("Failed to extract PolarsDataContext");
    }

    /// <summary>
    /// LINQ -> SQL -> LazyFrame -> DataFrame
    /// </summary>
    public static IPolarsDataFrame ToDataFrame<T>(this IQueryable<T> query, bool useStreaming = false)
    {
        var lf = query.ToLazyFrame();
        return lf.Collect(useStreaming);
    }
    /// <summary>
    /// Print Execuation Plan generated by Polars
    /// </summary>
    public static string Explain<T>(this IQueryable<T> query, bool optimized = true)
    {
        var lf = query.ToLazyFrame();

        return lf.Explain(optimized);
    }
}
