#pragma warning disable CS1591 
using Polars.NET.Core;
using LinqToDB.Internal.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Collections.Concurrent;

namespace Polars.NET.Linq;
/// <summary>
/// Provides a set of high-level extension methods for <see cref="IQueryable{T}"/> to bridge 
/// the gap between .NET LINQ expressions and the high-performance Polars execution engine.
/// </summary>
/// <remarks>
/// This class serves as the final integration layer of the Polars.NET.LINQ provider. 
/// It leverages <c>linq2db</c> to intercept expression trees, translates them into 
/// optimized SQL, and then injects that logic directly into the Polars Rust core 
/// via <see cref="IPolarsLazyFrame"/>. 
/// <para>
/// By using these extensions, developers can enjoy the strong typing and IDE support 
/// of LINQ while benefiting from Polars' data processing speeds and 
/// memory efficiency.
/// </para>
/// </remarks>
public static class PolarsQueryableExtensions
{
    private static IPolarsLazyFrame TranslateAndExecute(IExpressionQuery exprQuery, PolarsDataContext db)
    {
        var sqlQueries = exprQuery.GetSqlQueries(null);

        if (sqlQueries == null || sqlQueries.Count == 0)
            throw new InvalidOperationException("[Polars.NET] linq2db SQL generation failed");
        var rawSql = sqlQueries[0].Sql;
        var sanitizedSql = SqlSanitizer.Clean(rawSql); 

        return db.ExecuteToLazyFrame(sanitizedSql);
    }
    /// <summary>
    /// Translates the LINQ expression tree into a Polars execution plan without executing the query.
    /// This represents the "Logic-to-Logic" phase: LINQ -> SQL -> <see cref="IPolarsLazyFrame"/>.
    /// </summary>
    /// <typeparam name="T">The record or class type being queried.</typeparam>
    /// <param name="query">The <see cref="IQueryable{T}"/> source, typically created from a <see cref="PolarsDataContext"/>.</param>
    /// <returns>An <see cref="IPolarsLazyFrame"/> representing the optimized Polars execution plan.</returns>
    /// <exception cref="InvalidOperationException">
    /// Thrown if the LINQ expression cannot be converted to SQL by linq2db, or if the query provider is not a valid <see cref="PolarsDataContext"/>.
    /// </exception>
    public static IPolarsLazyFrame ToLazyFrame<T>(this IQueryable<T> query)
    {
        // ==========================================
        // Fast Path: Method Chain
        // ==========================================
        if (query is IExpressionQuery fastQuery && fastQuery.DataContext is PolarsDataContext fastDb)
        {
            return TranslateAndExecute(fastQuery, fastDb);
        }

        // ==========================================
        // Hacker Path：AST Rewrite ( F# query { })
        // ==========================================
        var rewriter = new FSharpAstRewriter();
        
        var cleanExpression = rewriter.Visit(query.Expression); 

        if (rewriter.Context != null && rewriter.Provider != null)
        {
            var pureQuery = rewriter.Provider.CreateQuery(cleanExpression);
            
            if (pureQuery is IExpressionQuery pureExprQuery)
            {
                return TranslateAndExecute(pureExprQuery, rewriter.Context);
            }
        }

        // ==========================================
        // Fallback
        // ==========================================
        throw new InvalidOperationException(
            $"[Polars.NET] Failed to unwrap query of type '{query.GetType().Name}'. " +
            "Ensure the query originates from a PolarsDataContext (e.g., db.RegisterTable).");
    }

    /// <summary>
    /// Materializes the LINQ query results into an in-memory <see cref="IPolarsDataFrame"/>.
    /// This triggers the actual data processing: LINQ -> SQL -> LazyFrame -> <see cref="IPolarsDataFrame"/>.
    /// </summary>
    /// <typeparam name="T">The record or class type being queried.</typeparam>
    /// <param name="query">The <see cref="IQueryable{T}"/> source.</param>
    /// <param name="useStreaming">
    /// If set to <see langword="true"/>, enables Polars' streaming execution engine for memory-intensive computations.
    /// </param>
    /// <returns>A materialized <see cref="IPolarsDataFrame"/> containing the query results.</returns>
    public static IPolarsDataFrame ToDataFrame<T>(this IQueryable<T> query, bool useStreaming = false)
    {
        var lf = query.ToLazyFrame();
        return lf.Collect(useStreaming);
    }

    /// <summary>
    /// Print Execuation Plan generated by Polars
    /// </summary>
    public static string Explain<T>(this IQueryable<T> query, bool optimized = true)
    {
        var lf = query.ToLazyFrame();

        return lf.Explain(optimized);
    }
}

internal class FSharpAstRewriter : ExpressionVisitor
{
    public IQueryProvider? Provider { get; private set; }
    public PolarsDataContext? Context { get; private set; }
    // 【核心新增】：零分配的结构体，用于安全缓存可能为 null 的 FieldInfo
    private readonly struct CachedField(FieldInfo? info)
    {
        public readonly FieldInfo? Info = info;
    }

    // 【核心新增】：静态全局缓存！
    private static readonly ConcurrentDictionary<Type, CachedField> _fieldCache = new();
    protected override Expression VisitConstant(ConstantExpression node)
    {
        if (node.Value != null && node.Value.GetType().IsGenericType && 
            node.Value.GetType().GetGenericTypeDefinition() == typeof(EnumerableQuery<>))
        {
            var bedrockQuery = DeepUnwrap(node.Value);
            
            if (bedrockQuery is IQueryable q && q is IExpressionQuery eq && eq.DataContext is PolarsDataContext db)
            {
                Provider = q.Provider;
                Context = db;
                
                return Expression.Constant(bedrockQuery, bedrockQuery.GetType());
            }
        }
        return base.VisitConstant(node);
    }

    private static object? DeepUnwrap(object? obj)
    {
        if (obj == null) return null;
        if (obj is IExpressionQuery) return obj; 

        if (obj is System.Collections.IEnumerable)
        {
            var type = obj.GetType();
            // O(1) 极速读取缓存！同一类型的迭代器，终生只执行一次反射！
            var cached = _fieldCache.GetOrAdd(type, t =>
            {
                var flags = BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Public;
                var sourceField = t.GetField("source", flags) ?? 
                                  t.GetField("_source", flags) ??
                                  t.GetField("enumerable", flags) ?? 
                                  t.GetField("_enumerable", flags);

                return new CachedField(sourceField);
            });

            if (cached.Info != null)
            {
                // 用缓存的 FieldInfo 直接取值，速度起飞
                return DeepUnwrap(cached.Info.GetValue(obj));
            }
        }
        return obj;
    }
}